name: networking
description: Networking package in flutter
version: 1.1.0
author: Koc Sistem
# homepage:
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_cache_manager: ^3.3.0
  json_serializable: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0 

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null